#!/bin/bash
while true; do
    action=x
    clear
    echo -ne "\n\n ACTION? v(Vol) b(bright) k(kbd) t(touchpad):\n\n    "
    read -r -n 1 action
    clear
    if [[ "$action" = "v" ]]; then
        while true; do
            echo -ne "\n\n Change VOL?  j(dec) k(inc) q(quit):\n\n    "
            amixer get Master | tail -n 1
            read -r -n 1 change
            if [[ "$change" = "k" ]]; then
                amixer set Master 3+
                clear
            elif [[ "$change" = "j" ]]; then
                amixer set Master 3-
                clear
            elif [[ "$change" != "q" ]]; then
                clear
                continue
            else
                break
            fi
        done
        break
    elif [[ "$action" = "b" ]]; then
        while true; do
            echo -ne "\n\n Change Brightness?  j(dec) k(inc) q(quit):\n\n    "
            brightnessctl g
            read -r -n 1 change
            if [[ "$change" = "k" ]]; then
                brightnessctl set 3%+
                clear
            elif [[ "$change" = "j" ]]; then
                brightnessctl set 3%-
                clear
            elif [[ "$change" != "q" ]]; then
                clear
                continue
            else
                break
            fi
        done
        break
    elif [[ "$action" = "k" ]]; then
        while true; do
            echo -ne "\n\n Keyboard Backlight?  j(dec) k(inc) q(quit):\n\n    "
            brightnessctl g --device="$(ls /sys/class/leds | rg kbd)"
            read -r -n 1 change
            if [[ "$change" = "k" ]]; then
                brightnessctl --device="$(ls /sys/class/leds | rg kbd)" set 1+
                clear
            elif [[ "$change" = "j" ]]; then
                brightnessctl --device="$(ls /sys/class/leds | rg kbd)" set 1-
                clear
            elif [[ "$change" != "q" ]]; then
                clear
                continue
            else
                break
            fi
        done
        break
    elif [[ "$action" = "t" ]]; then
        toggle_touchpad
        break
    elif [[ "$action" = "q" ]]; then
        break
    else
        echo -ne "\n\n BAD CHOICE"
        sleep 1
    fi
done
